version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - w3stside
  - anxolin
  - alfetopito
  labels:
  - DEPENDABOT
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: "@amcharts/amcharts4"
    versions:
    - 4.10.16
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.20
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.17
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.17
  rebase-strategy: disabled
